### ISSUE TITLE
Pads starting with number are not listed

### ISSUE THREAD

**Issue by JirkaV** [JohnMcLear/ep_list_pads#4]
We have a few pads with names starting with a number, not letter (e.g. "2014tasks"). These are not included in the list (casual look at the code shows that "letter" is used in a few places).

Unfortunately I'm not skilled enough in JS/Node to offer a fix and pull request, but looks like something that shouldn't be too difficult to change.

**Comment by JohnMcLear** [comment]
Done.

**Comment by JirkaV** [comment]
Thanks!
