### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by julpec** [JohnMcLear/ep_list_pads#9]
The links from the letters does not return to the page when using a subdirectory for the etherpad instance url.

My etherpad url is `https://example.org/pad/` and the links point to `https://example.org/list/<letter>`

So, the server url should be dynamically integrated.

**Comment by JohnMcLear** [comment]
To be fair, Etherpad doesn't at any point state that subdirectories are supported :P  But I will *fix*

**Comment by JohnMcLear** [comment]
Fixed and published :)
